### ISSUE TITLE
Set default branch to development

### ISSUE THREAD

**Issue by mkasztelnik** [dice-cyfronet/hyperflow-amqp-executor#2]
I just discovered that you are using `develop` instead of `master` for development. I propose to set it as default branch on github.

/cc @balis, @kfigiela, @mpawlik

**Comment by mpawlik** [comment]
I still believe that proper versioning and releasing of this project is "doable" :) So I'm for :-1:

**Comment by mkasztelnik** [comment]
@mpawlik I'm not against versioning and releasing - my point is that when I'm cloning this repository of visiting main webpage I see master branch, where code is outdated...

Another possibility (maybe even better :smiling_imp:) is to use `master` branch as main code branch.

**Comment by kfigiela** [comment]
We agreed to use git-flow workflow and I think that we should keep that, so
that development is done on devlop branch. Setting main branch for develop
for the time being is reasonable.

On Mon, Jan 26, 2015 at 9:43 PM, Marek Kasztelnik notifications@github.com
wrote:

> @mpawlik https://github.com/mpawlik I'm not against versioning and
> releasing - my point is that when I'm cloning this repository of visiting
> main webpage I see master branch, where code is outdated...
> 
> Another possibility (maybe even better [image: :smiling_imp:]) is to use
> master branch as main code branch.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/dice-cyfronet/hyperflow-amqp-executor/issues/2#issuecomment-71534194
> .

## 

Pozdrawiam,
Kamil Figiela

**Comment by mpawlik** [comment]
I was thinking rather about someone not from the dev team. In ideal world an outside guy would clone the repository and get the latest release (reasonably "up to date"). If we do set the default branch to develop, he will get a hot development version (unreleased).

On the other hand, we don't expect flood of outsiders, and our releases aren't that snappy, so it probably won't hurt anyone.

I'm switching it now, as we reached a majority.
